yatube/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),

]

yatube/users/urls.py
from django.contrib.auth.views import (
    LoginView,
    LogoutView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordChangeView,
    PasswordChangeDoneView,
)

from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/',
         LoginView.as_view(template_name='users/login.html'),
         name='login'
         ),
    path('pass_reset/', PasswordResetView.as_view(
         template_name='users/password_reset_form.html'),
         name='pass_reset'
         ),
    path('pass_reset_confirm/', PasswordResetConfirmView.as_view(
         template_name='users/password_reset_confirm.html'),
         name='pass_reset_confirm'
         ),
    path('pass_reset_done/', PasswordResetDoneView.as_view(
         template_name='users/password_reset_done.html'),
         name='pass_reset_done'
         ),
    path('pass_change/', PasswordChangeView.as_view(
         template_name='users/password_change_form.html'),
         name='pass_change'
         ),
    path('pass_change_done/', PasswordChangeDoneView.as_view(
         template_name='users/password_change_done.html'),
         name='pass_change_done'
         ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/templates/includes/footer.html
<!DOCTYPE html>
<html lang="ru">
<p>© {{ year }} Copyright <span style="color:red">Ya</span>tube</p>
</html>

yatube/templates/includes/header.html
<!DOCTYPE html>
{% load static %}
{% with request.resolver_match.view_name as view_name %}
<nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand" href="{% url 'posts:index' %}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">Ya</span>tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}">Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}">Технологии</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link
               {% if view_name  == 'posts:post_create' %}
              active
            {% endif %}"
            href="{% url 'posts:post_create' %}">Новая запись</a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name == 'users:pass_change' %}
                active
              {% endif %} link-light"
              href="{% url 'users:pass_change' %}">Изменить пароль</a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'users:logged_out' %}
                active
              {% endif %} link-light"
              href="{% url 'users:logout' %}">Выйти</a>
          </li>
          <li>
            Пользователь: {{ user.username }}
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'users:login' %}
                active
              {% endif %} link-light"
              href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item">
            <a class="nav-link
              {% if view_name  == 'users:signup' %}
                active
              {% endif %} link-light"
              href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}
</html>