yatube/home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),

]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>', views.group_posts, name='group_list'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    """Описываем модель группы."""

    slug = models.SlugField(unique=True)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    """Описываем модель поста."""

    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True)
    author = models.ForeignKey(
        User,
        related_name='posts',
        on_delete=models.CASCADE,
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        related_name='posts',
        verbose_name="Группа",
        help_text='Выберите группу'
    )

    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('-pub_date',)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

yatube/posts/forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ("text", "group", "image",)

yatube/posts/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Post, Group, User
from .forms import PostForm

POSTS_PER_PAGE = 10
POST_PREVIEW_SIMBOLS = 30


def index(request):
    """Главная страница."""
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/index.html'
    context = {'page_obj': page_obj, }
    return render(request, template, context)


def group_posts(request, slug):
    """Страницца группы."""
    group = get_object_or_404(Group, slug=slug)
    post_list = Post.objects.filter(group=group).order_by('-pub_date')
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/group_list.html'
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, template, context)


def profile(request, username):
    user = get_object_or_404(User, username=username)
    post_list = user.posts.all().order_by('-pub_date')
    paginator = Paginator(post_list, POSTS_PER_PAGE)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    template = 'posts/profile.html'
    context = {
        'count': post_list.count(),
        'page_obj': page_obj,
        'user': user,
    }
    return render(request, template, context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    template = 'posts/post_detail.html'
    preview = post.text[:POST_PREVIEW_SIMBOLS]
    context = {
        'post': post,
        'count': post.author.posts.count(),
        'preview': preview,
    }
    return render(request, template, context)


@login_required
def post_create(request):
    template = 'posts/create_post.html'
    form = PostForm(request.POST or None)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:profile', post.author)
    context = {'form': form}
    return render(request, template, context)


@login_required
def post_edit(request, post_id):
    template = 'posts/create_post.html'
    is_edit = True
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        form = PostForm(
            request.POST or None,
            files=request.FILES or None,
            instance=post
        )
        if form.is_valid():
            post = form.save()
            return redirect('posts:post_detail', post.pk)
        form = PostForm(instance=post)
        context = {
            'post': post,
            'form': form,
            "is_edit": is_edit,
        }
        return render(request, template, context)
    else:
        return redirect('posts:post_detail', post.pk)

yatube/templates/posts/create_post.html
<!DOCTYPE html> 
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}
  {% if is_edit %}
    Редактировать пост
  {% else %}
    Новая запись
  {% endif %}
{% endblock %}
{% load static %}
{% block content %}
<body>
  <main>
    <div class="container py-5">
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              {% if is_edit %}
                Редактировать пост
              {% else %}
                Новая запись
              {% endif %}
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
				{% csrf_token %}

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      {{ form.text.label_tag }}
                      <span class="required text-danger" >*</span>
                    </label>

					{{ form.text|addclass:"form-control" }}


                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-image row my-3 p-3">
                    <label for="id_image">
                      {{ form.image.label_tag }}
                    </label>

                      {{ form.image }}

                    <small id="id_group-help" class="form-text text-muted">
                      Добавить картинку
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      {{ form.group.label_tag }}
                    </label>

                      {{ form.group }}

                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                    {% if is_edit%}Сохранить{% else %}Добавить{% endif%}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>
</body>
{% endblock %}

yatube/templates/posts/group_list.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
  Записи сообщества {{ group.title }}
{% endblock %}
{% load thumbnail %}
  <body>
    <main>
      {% block content %}
        <h2> {{ group.title }} </h2>
        <p> {{ group.description }} </p>
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: {{ post.author.get_full_name }}
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:'d E Y' }}
            </li>
          </ul>
          {% thumbnail post.image "150x100" crop="center" upscale=True as im %}
            <img class="card-img my-1" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text|linebreaksbr }}</p>
          {% if not forloop.last %}<hr>{% endif %}
        {% endfor %}
      {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
  </body>
</html>

yatube/templates/posts/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% load static %}
{% load thumbnail %}
  <body>
    <main>
      {% block content %}
        {% for post in page_obj %}
          <ul>
            <li>
              Автор: <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.get_full_name }} </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
          {% thumbnail post.image "150x100" crop="center" upscale=True as im %}
            <img class="card-img my-1" src="{{ im.url }}">
          {% endthumbnail %}
          <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
          {% if post.group %}
            <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
          {% endif %}
          {% if not forloop.last %}
            <hr>
          {% endif %}
        {% endfor %}
        {% include 'posts/includes/paginator.html' %}
      {% endblock %}
    </main>
  </body>
</html>

yatube/templates/posts/post_detail.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
Пост {{ post.text|truncatechars:30 }}
{% endblock %}
{% load static %}
{% load thumbnail %}
  <body>
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          {% block content %}
            <h3>Автор: <a href="{% url 'posts:profile' post.author.username %}">
              {{ post.author.get_full_name }}
                </a></h3>
            <h5>Всего постов: {{ count }} </h5>
            <h5>Дата публикации: {{ post.pub_date|date:"d E Y" }}</h5>
            {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
              <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
            <div class="form-group row my-3 p-3">
              <p>{{ post.text }}</p>
            </div>
            <li class="list-group-item">
              <a href="{% url 'posts:post_edit' post.pk %}">
                Редактировать запись
              </a>
            </li>
          {% endblock %}
        </aside>
      </div>
    </main>
  </body>
</html>

yatube/templates/posts/profile.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block title %}
Профиль пользователя {{ user.username }}
{% endblock %}
{% load static %}
{% load thumbnail %}
  <body>
    <main>
      <div class="container py-5">
        <h1>Все посты пользователя {{ user.username }} </h1>
        <h3>Всего постов: {{ count }} </h3>
        {% block content %}
          {% for post in page_obj %}
            <ul>
              <li>
                Автор: {{ post.author.get_full_name }}
              </li>
              <li>
                Дата публикации: {{ post.pub_date|date:"d E Y" }}
              </li>
            </ul>
            {% thumbnail post.image "150x100" crop="center" upscale=True as im %}
              <img class="card-img my-1" src="{{ im.url }}">
            {% endthumbnail %}
            <p>{{ post.text }}</p>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация</a>
            {% if post.group %}
              <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
            {% endif %}
            {% if not forloop.last %}
              <hr>
            {% endif %}
          {% endfor %}
          {% include 'posts/includes/paginator.html' %}
        {% endblock %}
      </div>
    </main>
  </body>
</html>

yatube/templates/posts/update_post.html
<!DOCTYPE html> 
<html lang="ru"> 
  <head>    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="../img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="../img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="../img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="../css/bootstrap.min.css">
    <title>Редактировать пост</title>
  </head>
  <body>	   
    <header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container">
          <a class="navbar-brand" href="../posts/index.html">
            <img src="../img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
            <span style="color:red">Ya</span>tube
          </a>        
          <ul class="nav  nav-pills">
            <li class="nav-item">              
              <a class="nav-link" href="../about/author.html">
                Об авторе
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="../about/tech.html">
                Технологии
              </a>
            </li>
            <!-- пункты меню видны только авторизованному пользователю -->
            <li class="nav-item">
              <a class="nav-link active" href="../posts/create_post.html">
                Новая запись
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/password_change_form.html">
                Изменить пароль
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/logged_out.html">Выйти</a>
            </li>
            <li>
              Пользователь: leo
            <li>
            <!-- конец пункты меню видны только авторизованному пользователю -->
            <!-- пункты меню видны только неавторизованному пользователю -->
            <li class="nav-item"> 
              <a class="nav-link link-light" href="../users/login.html">
                Войти
              </a>
            </li>
            <li class="nav-item"> 
              <a class="nav-link link-light " href="../users/signup.html">Регистрация</a>
            </li>
            <!-- конец пункты меню видны только неавторизованному пользователю -->        
          </ul>      
        </div>
      </nav> 
    </header>
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">       
                Редактировать пост             
              </div>
              <div class="card-body">        
                <form method="post" action="../posts/create_post.html">
                  <input type="hidden" name="csrfmiddlewaretoken" value="">            
                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста                  
                      <span class="required text-danger" >*</span>                  
                    </label>
                    <textarea name="text" cols="40" rows="10" class="form-control" required id="id_text">[Фокшаны.] Еще переходъ до Фокшанъ, во время котораго я ѣхалъ съ Монго. Человѣкъ пустой, но съ твердыми, хотя и ложными убѣжденіями. Генерал[у] по этому должно быть случаю, угодно было спрашивать о моемъ здоровьи. Свинья! К[о]вырялъ носъ и ничего не написалъ — вотъ 2 упрека за нын[ѣшній] день. Послѣдній упрекъ становится слишкомъ частъ, хотя походъ и можетъ служить въ немъ отчасти извиненіемъ. Отношенія мои съ товарищами становятся такъ пріятны, что мнѣ жалко бросить штабъ. Здоровье кажется (2) лучше.
                    </textarea>                
                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>                  
                  </div>            
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа                  
                    </label>
                    <select name="group" class="form-control" id="id_group">
                      <option value="">---------</option>
                      <option value="1" selected>Группа: Лев Толстой – зеркало русской революции</option>
                    </select>
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>
                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      Добавить
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
    <footer class="border-top text-center py-3">
      <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
    </footer>
  </body>
</html>